# addresspool.yaml
---
#apiVersion: metallb.io/v1beta1
apiVersion: metallb.io/v1
kind: IPAddressPool
metadata:
  name: custom-addresspool
  namespace: metallb-system
spec: 
  addresses:
  - 192.168.88.1-192.168.88.100